// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Synmetrix Team",
            "url": "https://github.com/synmetrix/synmetrix"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "description": "Check if the service is running",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.HealthResponse"
                        }
                    }
                }
            }
        },
        "/rpc/ensure_user": {
            "post": {
                "description": "Just-in-time user synchronization - creates user in Hasura if not exists, fetching data from Keycloak",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "actions"
                ],
                "summary": "Ensure user exists (JIT User Sync)",
                "parameters": [
                    {
                        "description": "Hasura Action Request with session_variables",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.HasuraActionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User data (id, display_name, email, avatar_url)",
                        "schema": {
                            "$ref": "#/definitions/handler.HasuraActionResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Missing or invalid user ID in session",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to sync user from Keycloak",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handler.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "Error code (optional)",
                    "type": "string",
                    "example": "INVALID_REQUEST"
                },
                "message": {
                    "description": "Error message",
                    "type": "string",
                    "example": "invalid request body"
                }
            }
        },
        "handler.HasuraActionRequest": {
            "type": "object",
            "properties": {
                "action": {
                    "type": "object",
                    "properties": {
                        "name": {
                            "description": "Action name",
                            "type": "string",
                            "example": "ensure_user_exists"
                        }
                    }
                },
                "input": {
                    "description": "Action input parameters (optional)",
                    "type": "object",
                    "additionalProperties": true
                },
                "session_variables": {
                    "description": "Session variables from Hasura JWT",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    },
                    "example": {
                        "x-hasura-user-id": "uuid-here"
                    }
                }
            }
        },
        "handler.HasuraActionResponse": {
            "type": "object",
            "properties": {
                "avatar_url": {
                    "description": "User avatar URL (optional)",
                    "type": "string",
                    "example": "https://example.com/avatar.jpg"
                },
                "display_name": {
                    "description": "User display name",
                    "type": "string",
                    "example": "John Doe"
                },
                "email": {
                    "description": "User email",
                    "type": "string",
                    "example": "john.doe@example.com"
                },
                "id": {
                    "description": "User UUID",
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                }
            }
        },
        "handler.HealthResponse": {
            "type": "object",
            "properties": {
                "service": {
                    "description": "Service name",
                    "type": "string",
                    "example": "go-actions"
                },
                "status": {
                    "description": "Service status",
                    "type": "string",
                    "example": "ok"
                },
                "version": {
                    "description": "Service version",
                    "type": "string",
                    "example": "1.0.0"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:3000",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Go Actions - Keycloak JIT User Sync API",
	Description:      "API for just-in-time user synchronization between Keycloak and Hasura",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
